#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/toto2/modular_toto2.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_toto2.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 The HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math
from collections.abc import Sequence

from ...configuration_utils import PreTrainedConfig
from ...utils import auto_docstring


@auto_docstring(checkpoint="Datadog/Toto-2.0-4m")
class Toto2Config(PreTrainedConfig):
    r"""
    Configuration for Toto 2, a decoder-only multivariate time-series foundation model. The architecture interleaves
    causal *time* attention layers (attending over the time axis, patched) with bidirectional *variate* attention
    layers (attending over the variate axis at a fixed time position). Linear layers use μP-style fan-in scaling,
    attention uses `1/head_dim` scaling (μP), and residual connections follow the τ-weighted scheme of u-μP.

    Args:
        patch_size (`int`, *optional*, defaults to 32):
            Number of time points per input patch.
        hidden_size (`int`, *optional*, defaults to 256):
            Model width (aka `d_model`).
        intermediate_size (`int`, *optional*, defaults to 688):
            MLP intermediate size (aka `d_ff`); the SwiGLU produces `2*intermediate_size` activations from
            `hidden_size` and contracts back to `hidden_size`.
        num_hidden_layers (`int`, *optional*, defaults to 4):
            Total number of transformer layers (time + variate).
        num_attention_heads (`int`, *optional*, defaults to 4):
            Number of query heads.
        num_key_value_heads (`int`, *optional*, defaults to 4):
            Number of key/value groups. `num_attention_heads // num_key_value_heads` > 1 enables GQA.
        head_dim (`int`, *optional*, defaults to 64):
            Head dimension for Q/K and V (kept identical for the converted 4M checkpoint).
        layer_group_size (`int`, *optional*, defaults to 4):
            Size of the time/variate layer group. Layers `i % layer_group_size` within a group are variate (when
            `variate_layer_first=True`) or the last `num_variate_layers_per_group` indices of the group (otherwise).
        num_variate_layers_per_group (`int`, *optional*, defaults to 1):
            Variate-attention layers per group.
        variate_layer_first (`bool`, *optional*, defaults to `False`):
            If `True`, variate layers come at the start of each group; if `False`, at the end.
        qk_norm (`bool`, *optional*, defaults to `False`):
            Apply RMSNorm to Q/K before attention.
        per_dim_scale (`bool`, *optional*, defaults to `True`):
            Apply a learned positive per-dimension scale to Q before attention (softplus-parameterized).
        use_xpos (`bool`, *optional*, defaults to `True`):
            Use RoPE with xPos extrapolation scaling on the time axis.
        partial_rotary_factor (`float`, *optional*, defaults to 0.5):
            Fraction of `head_dim` that is rotated by RoPE (the rest is passed through).
        rope_theta (`float`, *optional*, defaults to 10000.0):
            RoPE base.
        xpos_scale_base (`int`, *optional*, defaults to 256):
            xPos scale base.
        xpos_scale_exponent (`float`, *optional*, defaults to 1.0):
            xPos scale exponent (query side; key side uses `-xpos_scale_exponent`).
        attn_bias (`bool`, *optional*, defaults to `True`):
            Bias on attention linear projections.
        mlp_bias (`bool`, *optional*, defaults to `False`):
            Bias on MLP linear projections.
        norm_eps (`float`, *optional*, defaults to 1e-4):
            RMSNorm epsilon.
        residual_mult (`float`, *optional*, defaults to 0.75):
            τ-rule global residual multiplier (u-μP).
        residual_attn_ratio (`float`, *optional*, defaults to 5.13621546657774):
            τ-rule attention:MLP residual ratio (u-μP). Compute via
            `Toto2Config.compute_residual_attn_ratio(context_length, patch_size)`.
        quantiles (`Sequence[float]`, *optional*, defaults to `(0.1, ..., 0.9)`):
            Quantile levels predicted by the output head.
        num_output_patches (`int`, *optional*, defaults to 1):
            Number of future patches predicted per token of hidden state.
        context_length (`int`, *optional*, defaults to 4096):
            Default context length used by [`Toto2ForPrediction`] (also sets `max_position_embeddings`).
        attention_dropout (`float`, *optional*, defaults to 0.0):
            Attention dropout.
        initializer_range (`float`, *optional*, defaults to 0.02):
            Initializer std.
    """

    model_type = "toto2"
    keys_to_ignore_at_inference = []
    is_encoder_decoder = False

    def __init__(
        self,
        patch_size: int = 32,
        hidden_size: int = 256,
        intermediate_size: int = 688,
        num_hidden_layers: int = 4,
        num_attention_heads: int = 4,
        num_key_value_heads: int = 4,
        head_dim: int = 64,
        layer_group_size: int = 4,
        num_variate_layers_per_group: int = 1,
        variate_layer_first: bool = False,
        qk_norm: bool = False,
        per_dim_scale: bool = True,
        use_xpos: bool = True,
        partial_rotary_factor: float = 0.5,
        rope_theta: float = 10000.0,
        xpos_scale_base: int = 256,
        xpos_scale_exponent: float = 1.0,
        attn_bias: bool = True,
        mlp_bias: bool = False,
        norm_eps: float = 1e-4,
        residual_mult: float = 0.75,
        residual_attn_ratio: float = 5.136215466577748,
        quantiles: Sequence[float] = (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9),
        num_output_patches: int = 1,
        context_length: int = 4096,
        attention_dropout: float = 0.0,
        initializer_range: float = 0.02,
        hidden_act: str = "silu",
        **kwargs,
    ):
        self.patch_size = patch_size
        self.hidden_size = hidden_size
        self.intermediate_size = intermediate_size
        self.num_hidden_layers = num_hidden_layers
        self.num_attention_heads = num_attention_heads
        self.num_key_value_heads = num_key_value_heads
        self.head_dim = head_dim
        self.layer_group_size = layer_group_size
        self.num_variate_layers_per_group = num_variate_layers_per_group
        self.variate_layer_first = variate_layer_first
        self.qk_norm = qk_norm
        self.per_dim_scale = per_dim_scale
        self.use_xpos = use_xpos
        self.partial_rotary_factor = partial_rotary_factor
        self.rope_theta = rope_theta
        self.xpos_scale_base = xpos_scale_base
        self.xpos_scale_exponent = xpos_scale_exponent
        self.attn_bias = attn_bias
        self.mlp_bias = mlp_bias
        self.rms_norm_eps = norm_eps
        self.residual_mult = residual_mult
        self.residual_attn_ratio = residual_attn_ratio
        self.quantiles = list(quantiles)
        self.num_output_patches = num_output_patches
        self.context_length = context_length
        self.max_position_embeddings = context_length
        self.attention_dropout = attention_dropout
        self.initializer_range = initializer_range
        self.hidden_act = hidden_act

        assert num_hidden_layers % layer_group_size == 0, (
            f"num_hidden_layers ({num_hidden_layers}) must be divisible by layer_group_size ({layer_group_size})"
        )
        assert num_attention_heads % num_key_value_heads == 0, (
            f"num_attention_heads ({num_attention_heads}) must be divisible by num_key_value_heads "
            f"({num_key_value_heads})"
        )

        super().__init__(**kwargs)

    @staticmethod
    def compute_residual_attn_ratio(context_length: int, patch_size: int) -> float:
        """u-μP default: `sqrt(S / log(S))` with `S = context_length / patch_size`."""
        s = context_length / patch_size
        return math.sqrt(s / math.log(s))

    def is_variate_layer(self, layer_idx: int) -> bool:
        mod = layer_idx % self.layer_group_size
        if self.variate_layer_first:
            return mod < self.num_variate_layers_per_group
        return mod >= self.layer_group_size - self.num_variate_layers_per_group


__all__ = ["Toto2Config"]
