#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/toto2/modular_toto2.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_toto2.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 The HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

from huggingface_hub.dataclasses import strict

from ...configuration_utils import PreTrainedConfig
from ...utils import auto_docstring


@auto_docstring(checkpoint="Datadog/Toto-2.0-4m")
@strict
class Toto2Config(PreTrainedConfig):
    r"""
    layer_group_size (`int`, *optional*, defaults to 4):
        Size of one time/variate layer group. Within each group `num_variate_layers_per_group` layers run
        cross-variate attention; the rest run causal time attention.
    num_variate_layers_per_group (`int`, *optional*, defaults to 1):
        Number of variate-attention layers in each group.
    variate_layer_first (`bool`, *optional*, defaults to `False`):
        If `True`, variate layers come at the start of each group; if `False`, at the end.
    qk_norm (`bool`, *optional*, defaults to `False`):
        Apply RMSNorm to Q/K before attention.
    per_dim_scale (`bool`, *optional*, defaults to `True`):
        Apply a learned positive per-dimension scale to Q before attention (softplus-parameterized).
    use_xpos (`bool`, *optional*, defaults to `True`):
        Use xPos length-extrapolation scaling on the time-axis rotary embedding.
    partial_rotary_factor (`float`, *optional*, defaults to 0.5):
        Fraction of `head_dim` rotated by RoPE; the rest is passed through.
    rope_theta (`float`, *optional*, defaults to 10000.0):
        RoPE base frequency.
    xpos_scale_base (`int`, *optional*, defaults to 256):
        xPos scale base.
    xpos_scale_exponent (`float`, *optional*, defaults to 1.0):
        xPos scale exponent (query side; key side uses `-xpos_scale_exponent`).
    attn_bias (`bool`, *optional*, defaults to `True`):
        Bias on attention linear projections.
    residual_mult (`float`, *optional*, defaults to 0.75):
        Default value for the per-layer τ scalars used in u-μP-style weighted residual connections; the
        actual per-layer values come from the checkpoint into `attn_tau` / `mlp_tau` buffers.
    quantiles (`Sequence[float]`, *optional*, defaults to `(0.1, 0.2, ..., 0.9)`):
        Quantile knots predicted by the output head.
    num_output_patches (`int`, *optional*, defaults to 1):
        Number of future patches predicted per token of hidden state.

    ```python
    >>> from transformers import Toto2Config, Toto2ForPrediction

    >>> configuration = Toto2Config()
    >>> model = Toto2ForPrediction(configuration)
    >>> configuration = model.config
    ```
    """

    model_type = "toto2"
    keys_to_ignore_at_inference = []
    is_encoder_decoder = False

    patch_size: int = 32
    hidden_size: int = 256
    intermediate_size: int = 688
    num_hidden_layers: int = 4
    num_attention_heads: int = 4
    num_key_value_heads: int = 4
    head_dim: int = 64
    layer_group_size: int = 4
    num_variate_layers_per_group: int = 1
    variate_layer_first: bool = False
    qk_norm: bool = False
    per_dim_scale: bool = True
    use_xpos: bool = True
    partial_rotary_factor: float = 0.5
    rope_theta: float = 10000.0
    xpos_scale_base: int = 256
    xpos_scale_exponent: float = 1.0
    attn_bias: bool = True
    mlp_bias: bool = False
    rms_norm_eps: float = 1e-4
    residual_mult: float = 0.75
    quantiles: list[float] | tuple[float, ...] = (0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9)
    num_output_patches: int = 1
    max_position_embeddings: int = 4096
    attention_dropout: float = 0.0
    initializer_range: float = 0.02
    hidden_act: str = "silu"

    def is_variate_layer(self, layer_idx: int) -> bool:
        mod = layer_idx % self.layer_group_size
        if self.variate_layer_first:
            return mod < self.num_variate_layers_per_group
        return mod >= self.layer_group_size - self.num_variate_layers_per_group


__all__ = ["Toto2Config"]
