#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
#           This file was automatically generated from src/transformers/models/toto2/modular_toto2.py.
#               Do NOT edit this file manually as any edits will be overwritten by the generation of
#             the file from the modular. If any change should be done, please apply the change to the
#                          modular_toto2.py file directly. One of our CI enforces this.
#                🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨🚨
# Copyright 2026 The HuggingFace Team. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import math
from collections.abc import Callable
from dataclasses import dataclass

import torch
import torch.nn as nn
import torch.nn.functional as F

from ...activations import ACT2FN
from ...integrations import use_kernel_forward_from_hub
from ...modeling_outputs import BaseModelOutput
from ...modeling_utils import ALL_ATTENTION_FUNCTIONS, PreTrainedModel
from ...processing_utils import Unpack
from ...utils import TransformersKwargs, auto_docstring, can_return_tuple, logging
from ...utils.output_capturing import capture_outputs
from .configuration_toto2 import Toto2Config


logger = logging.get_logger(__name__)


@dataclass
@auto_docstring
class Toto2ModelOutput(BaseModelOutput):
    r"""
    loc (`torch.Tensor` of shape `(batch, sequence_length, num_input_channels)`):
        Per-patch location used to standardize the input (broadcast to each token in the patch).
    scale (`torch.Tensor` of shape `(batch, sequence_length, num_input_channels)`):
        Per-patch scale used to standardize the input.
    """

    loc: torch.Tensor | None = None
    scale: torch.Tensor | None = None


@dataclass
@auto_docstring
class Toto2PredictionOutput(BaseModelOutput):
    r"""
    prediction_outputs (`torch.Tensor` of shape `(batch, prediction_length, num_input_channels)`):
        Point (median) forecast. Named to match [`PatchTSTForPredictionOutput.prediction_outputs`].
    quantiles (`torch.Tensor` of shape `(batch, prediction_length, num_input_channels, num_quantiles)`):
        Quantile forecasts for each knot in `config.quantiles` along the last axis.
    loss (`torch.Tensor` of shape `(1,)`, *optional*):
        Quantile loss when `future_values` is provided.
    """

    prediction_outputs: torch.Tensor | None = None
    quantiles: torch.Tensor | None = None
    loss: torch.Tensor | float | None = None


@use_kernel_forward_from_hub("RMSNorm")
class Toto2RMSNorm(nn.Module):
    """RMSNorm as in Llama; `Toto2Config.norm_include_weight=False` gives a pure, unweighted norm."""

    def __init__(self, hidden_size: int, eps: float = 1e-4, include_weight: bool = False) -> None:
        """
        Toto2RMSNorm is equivalent to T5LayerNorm
        """
        super().__init__()
        self.weight = nn.Parameter(torch.ones(hidden_size))
        self.variance_epsilon = eps
        if not include_weight:
            # Freeze the weight to 1 and stop tracking it as a learnable parameter.
            self.weight = nn.Parameter(torch.ones(hidden_size), requires_grad=False)

    def forward(self, hidden_states: torch.Tensor) -> torch.Tensor:
        input_dtype = hidden_states.dtype
        hidden_states = hidden_states.to(torch.float32)
        variance = hidden_states.pow(2).mean(-1, keepdim=True)
        hidden_states = hidden_states * torch.rsqrt(variance + self.variance_epsilon)
        return self.weight * hidden_states.to(input_dtype)

    def extra_repr(self):
        return f"{tuple(self.weight.shape)}, eps={self.variance_epsilon}"


# ---------------------------------------------------------------------------
# Rotary embedding (time axis). Toto2 uses a non-standard interleaved rotation plus optional
# xPos length-extrapolation scaling. We convert the checkpoint's QK weights so that Llama's
# standard half-split rotation gives the same result, and apply xPos scaling on top here.
# ---------------------------------------------------------------------------


class Toto2RotaryEmbedding(nn.Module):
    """Partial RoPE (first `partial_rotary_factor * head_dim` dimensions are rotated) with optional xPos scaling.

    The convert script permutes the Q and K projection rows so that the cached *interleaved* knot positions line up
    with Llama's *half-split* rotate convention — this keeps the module standard-shaped while matching the original
    output.
    """

    inv_freq: torch.Tensor

    def __init__(self, config: Toto2Config):
        super().__init__()
        self.config = config
        self.rotary_dim = int(round(config.head_dim * config.partial_rotary_factor))
        assert self.rotary_dim % 2 == 0, "rotary_dim must be even"

        inv_freq = 1.0 / (
            config.rope_theta ** (torch.arange(0, self.rotary_dim, 2, dtype=torch.float32) / self.rotary_dim)
        )
        self.register_buffer("inv_freq", inv_freq, persistent=False)

        if config.use_xpos:
            # xPos base-scale per dimension pair: (arange + 0.4*D) / (1.4*D)
            xpos_base = (torch.arange(0, self.rotary_dim, 2, dtype=torch.float32) + 0.4 * self.rotary_dim) / (
                1.4 * self.rotary_dim
            )
            self.register_buffer("xpos_base", xpos_base, persistent=False)
        else:
            self.xpos_base = None

    @torch.no_grad()
    def forward(self, x: torch.Tensor, position_ids: torch.Tensor):
        # position_ids shape: [T] or [B, T]. We reshape to ensure output broadcasts over (heads).
        if position_ids.dim() == 1:
            position_ids = position_ids.unsqueeze(0)
        freqs = position_ids[..., None].to(torch.float32) * self.inv_freq  # [B, T, D/2]
        emb = torch.cat((freqs, freqs), dim=-1)  # [B, T, D]
        cos = emb.cos().to(dtype=x.dtype)
        sin = emb.sin().to(dtype=x.dtype)
        return cos, sin

    def xpos_scale(self, position_ids: torch.Tensor, sign: float, dtype: torch.dtype) -> torch.Tensor | None:
        if self.xpos_base is None:
            return None
        if position_ids.dim() == 1:
            position_ids = position_ids.unsqueeze(0)
        max_pos = position_ids.max()
        center = torch.div(max_pos + 1, 2, rounding_mode="floor")
        power = (position_ids.float() - center) / self.config.xpos_scale_base
        base_scale = self.xpos_base ** power[..., None]  # [B, T, D/2]
        base_scale = torch.cat((base_scale, base_scale), dim=-1)  # [B, T, D]
        return (base_scale ** (sign * self.config.xpos_scale_exponent)).to(dtype=dtype)


# ---------------------------------------------------------------------------
# Per-dimension scale (u-μP).
# ---------------------------------------------------------------------------


class Toto2PerDimScale(nn.Module):
    """Learned positive per-dimension scaling applied to Q before attention.

    The stored parameter `per_dim_scale` is the *raw* one; the effective multiplier is
    `softplus(per_dim_scale) / log(2)` so that zero-init yields unit scaling. At conversion we bake the
    `u-μP` normalization constant (0.52103) into the stored parameter so that standard `softplus(p)/log(2)` produces
    the same output as the reference.
    """

    def __init__(self, dim: int):
        super().__init__()
        self.per_dim_scale = nn.Parameter(torch.zeros(dim))

    def forward(self, x: torch.Tensor) -> torch.Tensor:
        r = (F.softplus(self.per_dim_scale) / math.log(2.0)).to(x.dtype)
        return x * r


class Toto2MLP(nn.Module):
    """Llama-style SwiGLU MLP. Bias is optional (`config.mlp_bias`)."""

    def __init__(self, config: Toto2Config):
        super().__init__()
        self.config = config
        self.hidden_size = config.hidden_size
        self.intermediate_size = config.intermediate_size
        self.gate_proj = nn.Linear(config.hidden_size, config.intermediate_size, bias=config.mlp_bias)
        self.up_proj = nn.Linear(config.hidden_size, config.intermediate_size, bias=config.mlp_bias)
        self.down_proj = nn.Linear(config.intermediate_size, config.hidden_size, bias=config.mlp_bias)
        self.act_fn = ACT2FN[config.hidden_act]

    def forward(self, x):
        down_proj = self.down_proj(self.act_fn(self.gate_proj(x)) * self.up_proj(x))
        return down_proj


def repeat_kv(hidden_states: torch.Tensor, n_rep: int) -> torch.Tensor:
    """
    This is the equivalent of torch.repeat_interleave(x, dim=1, repeats=n_rep). The hidden states go from (batch,
    num_key_value_heads, seqlen, head_dim) to (batch, num_attention_heads, seqlen, head_dim)
    """
    batch, num_key_value_heads, slen, head_dim = hidden_states.shape
    if n_rep == 1:
        return hidden_states
    hidden_states = hidden_states[:, :, None, :, :].expand(batch, num_key_value_heads, n_rep, slen, head_dim)
    return hidden_states.reshape(batch, num_key_value_heads * n_rep, slen, head_dim)


def eager_attention_forward(
    module: nn.Module,
    query: torch.Tensor,
    key: torch.Tensor,
    value: torch.Tensor,
    attention_mask: torch.Tensor | None,
    scaling: float,
    dropout: float = 0.0,
    **kwargs: Unpack[TransformersKwargs],
):
    key_states = repeat_kv(key, module.num_key_value_groups)
    value_states = repeat_kv(value, module.num_key_value_groups)

    attn_weights = torch.matmul(query, key_states.transpose(2, 3)) * scaling
    if attention_mask is not None:
        attn_weights = attn_weights + attention_mask

    attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(query.dtype)
    attn_weights = nn.functional.dropout(attn_weights, p=dropout, training=module.training)
    attn_output = torch.matmul(attn_weights, value_states)
    attn_output = attn_output.transpose(1, 2).contiguous()

    return attn_output, attn_weights


def rotate_half(x: torch.Tensor) -> torch.Tensor:
    half = x.shape[-1] // 2
    return torch.cat((-x[..., half:], x[..., :half]), dim=-1)


def apply_rotary_with_xpos(
    q: torch.Tensor,
    k: torch.Tensor,
    cos: torch.Tensor,
    sin: torch.Tensor,
    q_xpos: torch.Tensor | None,
    k_xpos: torch.Tensor | None,
    rotary_dim: int,
    unsqueeze_dim: int = 1,
) -> tuple[torch.Tensor, torch.Tensor]:
    """Apply partial rotary to the first `rotary_dim` dims of q/k; the rest pass through unchanged.

    `q_xpos` / `k_xpos` (when not None) multiply the rotated half in-place with the xPos scale."""
    cos = cos.unsqueeze(unsqueeze_dim)
    sin = sin.unsqueeze(unsqueeze_dim)

    q_rot, q_pass = q[..., :rotary_dim], q[..., rotary_dim:]
    k_rot, k_pass = k[..., :rotary_dim], k[..., rotary_dim:]
    q_rot = q_rot * cos + rotate_half(q_rot) * sin
    k_rot = k_rot * cos + rotate_half(k_rot) * sin
    if q_xpos is not None:
        q_rot = q_rot * q_xpos.unsqueeze(unsqueeze_dim)
    if k_xpos is not None:
        k_rot = k_rot * k_xpos.unsqueeze(unsqueeze_dim)
    return torch.cat((q_rot, q_pass), dim=-1), torch.cat((k_rot, k_pass), dim=-1)


# ---------------------------------------------------------------------------
# Attention — custom: xPos, partial RoPE, per-dim Q scale, optional QK norm, μP `1/head_dim` scaling.
# ---------------------------------------------------------------------------


class Toto2Attention(nn.Module):
    """Toto2 self-attention. Matches `LlamaAttention`'s projection layout (separate q/k/v/o) but uses partial RoPE
    with xPos, a learned per-dimension Q scale, and μP `1/head_dim` attention scaling. Variate layers skip causal
    masking and skip RoPE entirely (position has no meaning across the variate axis)."""

    def __init__(self, config: Toto2Config, layer_idx: int):
        super().__init__()
        self.config = config
        self.layer_idx = layer_idx
        self.is_variate = config.is_variate_layer(layer_idx)
        self.head_dim = config.head_dim
        self.num_heads = config.num_attention_heads
        self.num_key_value_heads = config.num_key_value_heads
        self.num_key_value_groups = self.num_heads // self.num_key_value_heads
        # μP scaling: 1/d_k instead of 1/sqrt(d_k).
        self.scaling = 1.0 / self.head_dim
        self.attention_dropout = config.attention_dropout
        self.is_causal = not self.is_variate

        self.q_proj = nn.Linear(config.hidden_size, self.num_heads * self.head_dim, bias=config.attn_bias)
        self.k_proj = nn.Linear(config.hidden_size, self.num_key_value_heads * self.head_dim, bias=config.attn_bias)
        self.v_proj = nn.Linear(config.hidden_size, self.num_key_value_heads * self.head_dim, bias=config.attn_bias)
        self.o_proj = nn.Linear(self.num_heads * self.head_dim, config.hidden_size, bias=config.attn_bias)

        if config.qk_norm:
            self.q_norm = Toto2RMSNorm(self.head_dim, eps=config.rms_norm_eps, include_weight=False)
            self.k_norm = Toto2RMSNorm(self.head_dim, eps=config.rms_norm_eps, include_weight=False)
        else:
            self.q_norm = None
            self.k_norm = None

        if config.per_dim_scale:
            self.per_dim_scale = Toto2PerDimScale(self.head_dim)
        else:
            self.per_dim_scale = None

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
        xpos_scales: tuple[torch.Tensor | None, torch.Tensor | None] | None = None,
        attention_mask: torch.Tensor | None = None,
        rotary_dim: int | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> tuple[torch.Tensor, torch.Tensor | None]:
        input_shape = hidden_states.shape[:-1]
        q = self.q_proj(hidden_states).view(*input_shape, self.num_heads, self.head_dim).transpose(-3, -2)
        k = self.k_proj(hidden_states).view(*input_shape, self.num_key_value_heads, self.head_dim).transpose(-3, -2)
        v = self.v_proj(hidden_states).view(*input_shape, self.num_key_value_heads, self.head_dim).transpose(-3, -2)

        if self.q_norm is not None:
            q = self.q_norm(q)
            k = self.k_norm(k)
        if self.per_dim_scale is not None:
            q = self.per_dim_scale(q)

        if position_embeddings is not None and not self.is_variate:
            cos, sin = position_embeddings
            q_xpos, k_xpos = xpos_scales if xpos_scales is not None else (None, None)
            q, k = apply_rotary_with_xpos(q, k, cos, sin, q_xpos, k_xpos, rotary_dim)

        attention_interface: Callable = ALL_ATTENTION_FUNCTIONS.get_interface(
            self.config._attn_implementation, eager_attention_forward
        )
        attn_output, attn_weights = attention_interface(
            self,
            q,
            k,
            v,
            attention_mask,
            dropout=self.attention_dropout if self.training else 0.0,
            scaling=self.scaling,
            **kwargs,
        )
        attn_output = attn_output.reshape(*input_shape, -1).contiguous()
        return self.o_proj(attn_output), attn_weights


# ---------------------------------------------------------------------------
# τ-weighted residual rule (u-μP).
# ---------------------------------------------------------------------------


def _tau_rule(layer_idx: int, total_depth: int, residual_mult: float, residual_attn_ratio: float) -> float:
    """u-μP residual scaling rule. Matches `unit_scaling.transformer_residual_scaling_rule`: produces a τ per
    sub-layer (alternating attn/mlp, so 2*num_layers in total)."""
    frac = layer_idx / max(total_depth - 1, 1)
    # Blend attn-ratio at layer 0 → 1 at the last layer, then scale by global residual_mult.
    blend = residual_attn_ratio ** (1.0 - frac)
    return residual_mult * blend


class Toto2DecoderLayer(nn.Module):
    """One Toto2 transformer block with τ-weighted residuals:

    `hidden = (tau_a / sqrt(1 + tau_a^2)) * attn(norm(hidden)) + (1 / sqrt(1 + tau_a^2)) * hidden`
    `hidden = (tau_m / sqrt(1 + tau_m^2)) * mlp(norm(hidden)) + (1 / sqrt(1 + tau_m^2)) * hidden`

    where `tau_a`, `tau_m` are the per-layer τ values from the u-μP residual rule.
    """

    def __init__(self, config: Toto2Config, layer_idx: int):
        super().__init__()
        self.layer_idx = layer_idx
        self.is_variate = config.is_variate_layer(layer_idx)
        self.self_attn = Toto2Attention(config, layer_idx=layer_idx)
        self.mlp = Toto2MLP(config)
        self.norm1 = Toto2RMSNorm(
            config.hidden_size, eps=config.rms_norm_eps, include_weight=config.norm_include_weight
        )
        self.norm2 = Toto2RMSNorm(
            config.hidden_size, eps=config.rms_norm_eps, include_weight=config.norm_include_weight
        )

        total_depth = 2 * config.num_hidden_layers
        tau_a = _tau_rule(2 * layer_idx, total_depth, config.residual_mult, config.residual_attn_ratio)
        tau_m = _tau_rule(2 * layer_idx + 1, total_depth, config.residual_mult, config.residual_attn_ratio)
        denom_a = (1.0 + tau_a * tau_a) ** 0.5
        denom_m = (1.0 + tau_m * tau_m) ** 0.5
        self.register_buffer("attn_alpha", torch.tensor(tau_a / denom_a), persistent=False)
        self.register_buffer("attn_beta", torch.tensor(1.0 / denom_a), persistent=False)
        self.register_buffer("mlp_alpha", torch.tensor(tau_m / denom_m), persistent=False)
        self.register_buffer("mlp_beta", torch.tensor(1.0 / denom_m), persistent=False)

    def forward(
        self,
        hidden_states: torch.Tensor,
        position_embeddings: tuple[torch.Tensor, torch.Tensor] | None = None,
        xpos_scales: tuple[torch.Tensor | None, torch.Tensor | None] | None = None,
        attention_mask: torch.Tensor | None = None,
        rotary_dim: int | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> torch.Tensor:
        attn_out, _ = self.self_attn(
            self.norm1(hidden_states),
            position_embeddings=position_embeddings,
            xpos_scales=xpos_scales,
            attention_mask=attention_mask,
            rotary_dim=rotary_dim,
            **kwargs,
        )
        hidden_states = self.attn_alpha * attn_out + self.attn_beta * hidden_states

        mlp_out = self.mlp(self.norm2(hidden_states))
        hidden_states = self.mlp_alpha * mlp_out + self.mlp_beta * hidden_states
        return hidden_states


# ---------------------------------------------------------------------------
# Causal per-patch scaler (RevIN-style).
# ---------------------------------------------------------------------------


class Toto2PatchedCausalStdScaler(nn.Module):
    """Cumulative mean/std along the time axis, evaluated at patch boundaries and broadcast across each patch."""

    def __init__(self, patch_size: int, correction: float = 1.0, minimum_scale: float = 1e-6):
        super().__init__()
        self.patch_size = patch_size
        self.correction = correction
        self.minimum_scale = minimum_scale

    def forward(
        self, data: torch.Tensor, mask: torch.Tensor | None = None
    ) -> tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        hp = data.to(torch.float64) if data.is_floating_point() else data.to(torch.float32)
        if mask is None:
            mask = torch.ones_like(data, dtype=torch.bool)

        cum_data = (hp * mask).cumsum(dim=-1)
        denom = mask.cumsum(dim=-1).clamp_min(1)
        causal_loc = cum_data / denom

        prev_loc = torch.cat([torch.zeros_like(causal_loc[..., :1]), causal_loc[..., :-1]], dim=-1)
        delta = hp - prev_loc
        increment = delta * (hp - causal_loc) * mask
        m2 = increment.cumsum(dim=-1)
        causal_var = m2 / (denom - self.correction).clamp(min=1)
        causal_scale = causal_var.clamp_min(0).sqrt().clamp_min(self.minimum_scale)

        b = data.shape[:-1]
        seq_len = data.shape[-1]
        assert seq_len % self.patch_size == 0, (
            f"time length {seq_len} must be a multiple of patch_size {self.patch_size}"
        )
        loc = causal_loc.view(*b, -1, self.patch_size)[..., -1:].expand(*b, -1, self.patch_size).reshape(*b, seq_len)
        scale = (
            causal_scale.view(*b, -1, self.patch_size)[..., -1:].expand(*b, -1, self.patch_size).reshape(*b, seq_len)
        )
        loc, scale = loc.to(data.dtype), scale.to(data.dtype)
        return torch.where(mask, (data - loc) / scale, torch.zeros_like(data)), loc, scale


# ---------------------------------------------------------------------------
# Base / Pretrained.
# ---------------------------------------------------------------------------


@auto_docstring
class Toto2PreTrainedModel(PreTrainedModel):
    config: Toto2Config
    base_model_prefix = "model"
    main_input_name = "past_values"
    input_modalities = ("time",)
    _no_split_modules = ["Toto2DecoderLayer"]
    _supports_sdpa = True
    _supports_flash_attn = True
    _supports_flex_attn = True
    _can_record_outputs = {
        "hidden_states": Toto2DecoderLayer,
        "attentions": Toto2Attention,
    }

    @torch.no_grad()
    def _init_weights(self, module):
        super()._init_weights(module)
        # Reinitialize non-persistent buffers (τ schedule + RoPE / xPos tables) so that reloading the model
        # from meta device — which drops `persistent=False` buffers — produces the same outputs as a fresh init.
        if isinstance(module, Toto2DecoderLayer):
            total_depth = 2 * self.config.num_hidden_layers
            tau_a = _tau_rule(
                2 * module.layer_idx, total_depth, self.config.residual_mult, self.config.residual_attn_ratio
            )
            tau_m = _tau_rule(
                2 * module.layer_idx + 1, total_depth, self.config.residual_mult, self.config.residual_attn_ratio
            )
            denom_a = (1.0 + tau_a * tau_a) ** 0.5
            denom_m = (1.0 + tau_m * tau_m) ** 0.5
            module.attn_alpha.copy_(torch.tensor(tau_a / denom_a, dtype=module.attn_alpha.dtype))
            module.attn_beta.copy_(torch.tensor(1.0 / denom_a, dtype=module.attn_beta.dtype))
            module.mlp_alpha.copy_(torch.tensor(tau_m / denom_m, dtype=module.mlp_alpha.dtype))
            module.mlp_beta.copy_(torch.tensor(1.0 / denom_m, dtype=module.mlp_beta.dtype))
        elif isinstance(module, Toto2RotaryEmbedding):
            rotary_dim = module.rotary_dim
            inv_freq = 1.0 / (
                self.config.rope_theta ** (torch.arange(0, rotary_dim, 2, dtype=torch.float32) / rotary_dim)
            )
            module.inv_freq.copy_(inv_freq.to(device=module.inv_freq.device, dtype=module.inv_freq.dtype))
            if module.xpos_base is not None:
                xpos_base = (torch.arange(0, rotary_dim, 2, dtype=torch.float32) + 0.4 * rotary_dim) / (
                    1.4 * rotary_dim
                )
                module.xpos_base.copy_(xpos_base.to(device=module.xpos_base.device, dtype=module.xpos_base.dtype))


# ---------------------------------------------------------------------------
# Core model — multivariate, alternating time/variate attention.
# ---------------------------------------------------------------------------


class Toto2Model(Toto2PreTrainedModel):
    def __init__(self, config: Toto2Config):
        super().__init__(config)
        self.config = config
        self.scaler = Toto2PatchedCausalStdScaler(patch_size=config.patch_size)

        # Patch tokenizer: concatenate scaled patch + mask channel, project to hidden_size.
        self.patch_proj = nn.Sequential(
            nn.Linear(2 * config.patch_size, 4 * config.hidden_size),
            nn.SiLU(),
            nn.Linear(4 * config.hidden_size, config.hidden_size),
        )
        self.patch_skip = nn.Linear(2 * config.patch_size, config.hidden_size)

        self.layers = nn.ModuleList(
            [Toto2DecoderLayer(config, layer_idx) for layer_idx in range(config.num_hidden_layers)]
        )
        self.out_norm = Toto2RMSNorm(
            config.hidden_size, eps=config.rms_norm_eps, include_weight=config.norm_include_weight
        )
        self.rotary_emb = Toto2RotaryEmbedding(config)

        self.post_init()

    def _embed_patches(self, scaled: torch.Tensor, mask: torch.Tensor) -> torch.Tensor:
        # scaled, mask: [B, N, T]. Output: [B, N, S, D] where S = T / patch_size.
        bsz, nvar, time = scaled.shape
        p = self.config.patch_size
        s = time // p
        patch = scaled.view(bsz, nvar, s, p)
        mpatch = (~mask).to(scaled.dtype).view(bsz, nvar, s, p)
        x = torch.cat([patch, mpatch], dim=-1)
        return self.patch_proj(x) + self.patch_skip(x)

    @staticmethod
    def _build_causal_mask(seq_len: int, dtype: torch.dtype, device: torch.device) -> torch.Tensor:
        """Additive causal mask `[1, 1, S, S]` compatible with all `ALL_ATTENTION_FUNCTIONS` backends.

        We pass an explicit mask (rather than `is_causal=True`) so that eager/SDPA/FA2/flex all produce
        identical outputs; the eager fallback only looks at `attention_mask`."""
        min_value = torch.finfo(dtype).min
        causal = torch.triu(torch.full((seq_len, seq_len), min_value, dtype=dtype, device=device), diagonal=1)
        return causal.view(1, 1, seq_len, seq_len)

    def _run_stack(
        self, hidden: torch.Tensor, group_ids: torch.Tensor | None, time_ids: torch.Tensor | None
    ) -> torch.Tensor:
        # hidden: [B, N, S, D]
        bsz, nvar, seq, _ = hidden.shape
        device = hidden.device

        if time_ids is None:
            time_ids = torch.arange(seq, device=device, dtype=torch.long)
        position_embeddings = self.rotary_emb(hidden, time_ids)
        if self.rotary_emb.xpos_base is not None:
            q_scale = self.rotary_emb.xpos_scale(time_ids, sign=+1.0, dtype=hidden.dtype)
            k_scale = self.rotary_emb.xpos_scale(time_ids, sign=-1.0, dtype=hidden.dtype)
            xpos_scales = (q_scale, k_scale)
        else:
            xpos_scales = None

        causal_mask = self._build_causal_mask(seq, hidden.dtype, device)

        for layer in self.layers:
            if layer.is_variate:
                # reshape: [B, N, S, D] -> [B*S, N, D]  (attend across variates at each time; no mask)
                x = hidden.transpose(1, 2).reshape(bsz * seq, nvar, hidden.shape[-1])
                x = layer(x)
                hidden = x.view(bsz, seq, nvar, hidden.shape[-1]).transpose(1, 2).contiguous()
            else:
                # reshape: [B, N, S, D] -> [B*N, S, D]  (causal attend across time)
                x = hidden.reshape(bsz * nvar, seq, hidden.shape[-1])
                x = layer(
                    x,
                    position_embeddings=position_embeddings,
                    xpos_scales=xpos_scales,
                    attention_mask=causal_mask,
                    rotary_dim=self.rotary_emb.rotary_dim,
                )
                hidden = x.view(bsz, nvar, seq, hidden.shape[-1])

        return self.out_norm(hidden)

    @can_return_tuple
    @capture_outputs
    @auto_docstring
    def forward(
        self,
        past_values: torch.Tensor,
        past_observed_mask: torch.Tensor | None = None,
        series_ids: torch.Tensor | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> Toto2ModelOutput:
        r"""
        past_values (`torch.FloatTensor` of shape `(batch, sequence_length, num_input_channels)`):
            Multivariate time-series context. `sequence_length` must be a multiple of `config.patch_size`. Matches
            the axis convention used by [`PatchTSTModel`] / [`PatchTSMixerModel`].
        past_observed_mask (`torch.BoolTensor` of shape `(batch, sequence_length, num_input_channels)`, *optional*):
            `True` at observed positions, `False` at missing positions. Defaults to all-observed.
        series_ids (`torch.LongTensor` of shape `(batch, num_input_channels)`, *optional*):
            Series identifiers for the channel/variate axis, used to restrict cross-channel attention to matching
            ids. Defaults to zeros (single group).
        """
        # External convention (B, T, N); internal compute uses (B, N, T) to keep the stack's reshapes cheap.
        past_values_bnt = past_values.transpose(-1, -2)
        if past_observed_mask is None:
            past_observed_mask_bnt = torch.ones_like(past_values_bnt, dtype=torch.bool)
        else:
            past_observed_mask_bnt = past_observed_mask.transpose(-1, -2)

        scaled, loc, scale = self.scaler(past_values_bnt, past_observed_mask_bnt)
        scaled = scaled.asinh()
        hidden = self._embed_patches(scaled, past_observed_mask_bnt)
        hidden = self._run_stack(hidden, group_ids=series_ids, time_ids=None)

        # Return loc/scale back in (B, T, N) to match the input layout.
        return Toto2ModelOutput(last_hidden_state=hidden, loc=loc.transpose(-1, -2), scale=scale.transpose(-1, -2))


# ---------------------------------------------------------------------------
# Prediction head.
# ---------------------------------------------------------------------------


class Toto2ForPrediction(Toto2PreTrainedModel):
    def __init__(self, config: Toto2Config):
        super().__init__(config)
        self.config = config
        self.model = Toto2Model(config)

        # Quantile-knot head: project hidden_size -> (num_output_patches * patch_size * num_quantiles).
        out_size = config.num_output_patches * config.patch_size * len(config.quantiles)
        self.output_head = nn.Sequential(
            nn.Linear(config.hidden_size, 4 * config.hidden_size),
            nn.SiLU(),
            nn.Linear(4 * config.hidden_size, out_size),
        )
        self.output_skip = nn.Linear(config.hidden_size, out_size)

        self.post_init()

    @can_return_tuple
    @auto_docstring
    def forward(
        self,
        past_values: torch.Tensor,
        past_observed_mask: torch.Tensor | None = None,
        series_ids: torch.Tensor | None = None,
        prediction_length: int | None = None,
        future_values: torch.Tensor | None = None,
        **kwargs: Unpack[TransformersKwargs],
    ) -> Toto2PredictionOutput:
        r"""
        past_values (`torch.FloatTensor` of shape `(batch, sequence_length, num_input_channels)`):
            Multivariate context. `sequence_length` must be a multiple of `config.patch_size`.
        past_observed_mask (`torch.BoolTensor` of shape `(batch, sequence_length, num_input_channels)`, *optional*):
            `True` at observed positions, `False` at missing positions.
        series_ids (`torch.LongTensor` of shape `(batch, num_input_channels)`, *optional*):
            Series ids for cross-channel grouping on variate-attention layers.
        prediction_length (`int`, *optional*):
            Number of future steps to forecast. Defaults to `config.patch_size * config.num_output_patches` (one
            output patch per token). Longer horizons iterate the model in AR fashion with median feedback; that
            loop is not yet implemented in this scaffold.
        future_values (`torch.FloatTensor` of shape `(batch, prediction_length, num_input_channels)`, *optional*):
            Ground truth for quantile-loss computation.
        """
        outputs = self.model(
            past_values=past_values, past_observed_mask=past_observed_mask, series_ids=series_ids, **kwargs
        )
        hidden = outputs.last_hidden_state  # [B, N, S, D]

        num_q = len(self.config.quantiles)
        head = self.output_head(hidden) + self.output_skip(
            hidden
        )  # [B, N, S, patch_size * num_output_patches * num_q]
        head = head.view(*hidden.shape[:-1], self.config.num_output_patches, self.config.patch_size, num_q)

        # One-patch prediction: take the last source position and the first output patch. Shape (B, N, patch, Q).
        last_bnpq = head[..., -1, 0, :, :]
        # Rescale using per-patch loc/scale (from the last input patch) and sort along the quantile axis.
        loc = outputs.loc[:, -self.config.patch_size :, :].transpose(-1, -2).unsqueeze(-1)  # (B, N, patch, 1)
        scale = outputs.scale[:, -self.config.patch_size :, :].transpose(-1, -2).unsqueeze(-1)
        quant_bnpq = (last_bnpq.sinh() * scale + loc).sort(dim=-1).values

        # Convert to the transformers-convention output shape: (B, prediction_length, N, num_q).
        quantiles_btnq = quant_bnpq.permute(0, 2, 1, 3).contiguous()

        if 0.5 in self.config.quantiles:
            median_idx = self.config.quantiles.index(0.5)
        else:
            median_idx = num_q // 2
        prediction_outputs = quantiles_btnq[..., median_idx]  # (B, prediction_length, N)

        loss = None
        if future_values is not None:
            target_len = min(future_values.shape[1], quantiles_btnq.shape[1])
            errors = future_values[:, :target_len, :, None] - quantiles_btnq[:, :target_len, :, :]
            q = torch.tensor(self.config.quantiles, device=errors.device, dtype=errors.dtype)
            loss = torch.maximum((q - 1) * errors, q * errors).mean()

        if prediction_length is not None and prediction_length > quantiles_btnq.shape[1]:
            logger.warning(
                "Requested `prediction_length=%d` exceeds `config.patch_size * config.num_output_patches=%d`. "
                "AR decoding beyond one patch is not yet implemented in this scaffold; returning the "
                "single-patch forecast.",
                prediction_length,
                self.config.patch_size * self.config.num_output_patches,
            )

        return Toto2PredictionOutput(
            last_hidden_state=outputs.last_hidden_state,
            hidden_states=outputs.hidden_states,
            attentions=outputs.attentions,
            prediction_outputs=prediction_outputs,
            quantiles=quantiles_btnq,
            loss=loss,
        )


__all__ = ["Toto2Model", "Toto2ForPrediction", "Toto2PreTrainedModel"]
